name: "Test application"

on:
    pull_request:
    push:
        branches:
            - "master"
            - "[0-9]+.x"
            - "[0-9]+.[0-9]+"
            - "[0-9]+.[0-9]+.x"

jobs:
    test:
        name: "PHP ${{ matrix.php-version }}, Symfony ${{ matrix.symfony-version }} ${{ matrix.dependencies }}"
        runs-on: "ubuntu-20.04"
        env:
            SYMFONY_DEPRECATIONS_HELPER: weak

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: "8.0"
                      dependencies: "lowest"

                    - php-version: "8.0"
                      symfony-version: "6"

                    - php-version: "8.1"
                      symfony-version: "6"

        steps:
            - name: "Checkout project"
              uses: "actions/checkout@v2"

            - name: "Install and configure PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"
                  extensions: "pdo, pdo_sqlite"
                  tools: "composer:v2"

            - name: "Require Specific Symfony Version"
              if: "${{ matrix.symfony-version }}"
              run: composer require --no-update symfony/flex && composer config extra.symfony.require ${{ matrix.symfony-version}}

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"
                  composer-options: "--prefer-dist"

            - name: "Install phpunit"
              run: vendor/bin/simple-phpunit install

            - name: "Execute test cases"
              run: vendor/bin/simple-phpunit
